// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SocialCoding.API.Data;

namespace SocialCoding.API.Migrations
{
    [DbContext(typeof(SocialCodingContext))]
    [Migration("20190528224559_UsuarioExtension")]
    partial class UsuarioExtension
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("SocialCoding.API.Models.Imagen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("AgregadaEn");

                    b.Property<bool>("DePerfil");

                    b.Property<string>("Descripcion");

                    b.Property<string>("Url");

                    b.Property<int>("UsuarioId");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Imagenes");
                });

            modelBuilder.Entity("SocialCoding.API.Models.Lenguaje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("AgregadoEn");

                    b.Property<string>("Nombre");

                    b.Property<int?>("UsuarioId");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Lenguajes");
                });

            modelBuilder.Entity("SocialCoding.API.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Alias");

                    b.Property<string>("Ciudad");

                    b.Property<byte[]>("ContraHash");

                    b.Property<byte[]>("ContraSalt");

                    b.Property<DateTime>("CreadoEn");

                    b.Property<DateTime>("FechaNacimiento");

                    b.Property<string>("Genero");

                    b.Property<string>("NombreUsuario");

                    b.Property<string>("Pais");

                    b.Property<string>("TrabajaEn");

                    b.Property<DateTime>("UltimaSesion");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SocialCoding.API.Models.Valor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nombre");

                    b.HasKey("Id");

                    b.ToTable("Valores");
                });

            modelBuilder.Entity("SocialCoding.API.Models.Imagen", b =>
                {
                    b.HasOne("SocialCoding.API.Models.Usuario", "Usuario")
                        .WithMany("Imagenes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SocialCoding.API.Models.Lenguaje", b =>
                {
                    b.HasOne("SocialCoding.API.Models.Usuario")
                        .WithMany("Lenguajes")
                        .HasForeignKey("UsuarioId");
                });
#pragma warning restore 612, 618
        }
    }
}
