// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SocialCoding.API.Data;

namespace SocialCoding.API.Migrations
{
    [DbContext(typeof(SocialCodingContext))]
    [Migration("20190728160910_MensajesM")]
    partial class MensajesM
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("SocialCoding.API.Models.Imagen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("AgregadaEn");

                    b.Property<bool>("DePerfil");

                    b.Property<string>("Descripcion");

                    b.Property<string>("IdPublica");

                    b.Property<string>("Url");

                    b.Property<int>("UsuarioId");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Imagenes");
                });

            modelBuilder.Entity("SocialCoding.API.Models.MeGusta", b =>
                {
                    b.Property<int>("MeGustadorId");

                    b.Property<int>("MeGustaaId");

                    b.HasKey("MeGustadorId", "MeGustaaId");

                    b.HasIndex("MeGustaaId");

                    b.ToTable("MeGustas");
                });

            modelBuilder.Entity("SocialCoding.API.Models.Mensaje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Contenido");

                    b.Property<bool>("Leido");

                    b.Property<DateTime?>("LeidoEn");

                    b.Property<DateTime>("MensajeEnviado");

                    b.Property<int>("ReceptorId");

                    b.Property<bool>("ReceptorLoElimino");

                    b.Property<int>("RemitenteId");

                    b.Property<bool>("RemitenteLoElimino");

                    b.HasKey("Id");

                    b.HasIndex("ReceptorId");

                    b.HasIndex("RemitenteId");

                    b.ToTable("Mensajes");
                });

            modelBuilder.Entity("SocialCoding.API.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Alias");

                    b.Property<string>("Ciudad");

                    b.Property<byte[]>("ContraHash");

                    b.Property<byte[]>("ContraSalt");

                    b.Property<DateTime>("CreadoEn");

                    b.Property<DateTime>("FechaNacimiento");

                    b.Property<string>("Genero");

                    b.Property<string>("Hobbies");

                    b.Property<string>("Lenguajes");

                    b.Property<string>("NombreUsuario");

                    b.Property<string>("Pais");

                    b.Property<string>("TrabajaEn");

                    b.Property<DateTime>("UltimaSesion");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SocialCoding.API.Models.Valor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nombre");

                    b.HasKey("Id");

                    b.ToTable("Valores");
                });

            modelBuilder.Entity("SocialCoding.API.Models.Imagen", b =>
                {
                    b.HasOne("SocialCoding.API.Models.Usuario", "Usuario")
                        .WithMany("Imagenes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SocialCoding.API.Models.MeGusta", b =>
                {
                    b.HasOne("SocialCoding.API.Models.Usuario", "MeGustaa")
                        .WithMany("MeGustadores")
                        .HasForeignKey("MeGustaaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SocialCoding.API.Models.Usuario", "MeGustador")
                        .WithMany("MeGustas")
                        .HasForeignKey("MeGustadorId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SocialCoding.API.Models.Mensaje", b =>
                {
                    b.HasOne("SocialCoding.API.Models.Usuario", "Receptor")
                        .WithMany("MensajesRecibidos")
                        .HasForeignKey("ReceptorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SocialCoding.API.Models.Usuario", "Remitente")
                        .WithMany("MensajesEnviados")
                        .HasForeignKey("RemitenteId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
